# Generated by Django 5.0 on 2023-12-31 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug_crc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Drug_ID_MESH', models.IntegerField()),
                ('Drug', models.CharField(max_length=100)),
                ('Source_Plant', models.TextField()),
                ('Mechanism_of_action', models.TextField()),
                ('chemical_structure', models.URLField()),
                ('PMID', models.IntegerField()),
            ],
        ),
    ]
