# Generated by Django 5.0 on 2023-12-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NaturalDrug', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug_crc',
            name='Drug',
            field=models.CharField(max_length=200),
        ),
    ]
