# Generated by Django 5.0 on 2023-12-31 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metabol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metabolite_crc',
            name='Plant_Name',
            field=models.CharField(max_length=200),
        ),
    ]
