# Generated by Django 5.0 on 2024-01-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metabolo_crc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plant_Name', models.TextField()),
                ('Scientific_Name', models.TextField()),
                ('Family', models.TextField()),
                ('Metabolites', models.CharField(max_length=100)),
                ('Pathway', models.TextField()),
                ('References', models.URLField()),
            ],
        ),
    ]
